name: Acceptance Tests
on: [push,pull_request]

jobs:
  acceptance-ce:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
      id: go

    - name: Check out code repository source code
      uses: actions/checkout@v2

    - name: Start Gitlab
      run: make testacc-up

    - name: Run acceptance tests
      run: make testacc

  acceptance-ee:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
      id: go

    - name: Check out code repository source code
      uses: actions/checkout@v2

    - name: Set up Enterprise Edition License file
      run: |
        openssl version
        mkdir license
        [[ -n "${{ secrets.LICENSE_ENCRYPTION_PASSWORD }}" ]] && echo decrypt
        [[ -n "${{ secrets.LICENSE_ENCRYPTION_PASSWORD }}" ]] && openssl enc  -d -aes-256-cbc -pbkdf2 -iter 20000 -in Gitlab-license.encrypted -out Gitlab-license.txt -pass "pass:${{ secrets.LICENSE_ENCRYPTION_PASSWORD }}"
        chmod 666 Gitlab-license.txt || true

    - name: Start Gitlab
      run: make testacc-up

    - name: Run acceptance tests
      run: make testacc
