# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Automation for pull requests that requires "write" access.

name: pr-target

on: [pull_request_target]

permissions:
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v3
        with:
          configuration-path: .github/labeler-pr-triage.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Ignore generated files.
          IGNORED: |
            **/go.sum
            docs/**/*
        with:
          sizes: |
            {
              "0": "XS",
              "10": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
