name: test
on: [push,pull_request]

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v2
      - id: go-version
        run: echo "::set-output name=go-version::$(cat .go-version)"

  lint:
    runs-on: ubuntu-latest
    needs: [go-version]
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint-golangci
          - lint-tfprovider
          - lint-examples-tf
          - lint-examples-sh
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            bin
          key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}-include-tools
      - run: make ${{ matrix.target }}

  unit-test:
    runs-on: ${{ matrix.os }}
    needs: [go-version]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}-no-tools
      - run: make test

  generate-check:
    runs-on: ubuntu-latest
    needs: [go-version]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            bin
          key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}-include-tools
      - run: make generate
      - name: Check generated files
        run: |
          [ -z "$(git status --short)" ] || { echo "Error: Files should have been generated:"; git status --short; echo "Diff:"; git diff HEAD; exit 1; }

  acceptance-ce:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [go-version]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}-no-tools
      - run: make testacc-up
      - run: make testacc

  acceptance-ee:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [go-version]
    if: github.event_name == 'push' && github.repository_owner == 'gitlabhq'
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}-no-tools
      - run: |
          openssl version
          openssl enc -d -aes-256-cbc -pbkdf2 -iter 20000 -in Gitlab-license.encrypted -out Gitlab-license.txt -pass "pass:${{ secrets.LICENSE_ENCRYPTION_PASSWORD }}"
      - run: make testacc-up SERVICE=gitlab-ee
      - run: make testacc
